"""add completed_at and finish_duration on task

Revision ID: f2f506a31c01
Revises: 9e58337ba18c
Create Date: 2025-09-12 13:05:49.952656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f506a31c01'
down_revision: Union[str, None] = '9e58337ba18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('finish_duration', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('task', 'total_time_logged')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('total_time_logged', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('task', 'completed_at')
    op.drop_column('task', 'finish_duration')
    # ### end Alembic commands ###
