"""buat tabel proyek

Revision ID: 156f050a4602
Revises:
Create Date: 2025-08-09 11:44:18.746123

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '156f050a4602'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyek',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('TENDER', 'AKTIF', 'SELESAI', 'BATAL', name='statusproyek'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proyeks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proyek')
    op.execute("DROP TYPE IF EXISTS statusproyek;")
    # ### end Alembic commands ###
