"""buat tabel task_assignee

Revision ID: f33725a6ec54
Revises: f137cd8be077
Create Date: 2025-08-21 22:08:12.736796

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f33725a6ec54'
down_revision: Union[str, None] = 'f137cd8be077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_assignee',
    sa.Column('task_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_task_assignee_task_id_task')),
    sa.PrimaryKeyConstraint('task_id', 'user_id', name=op.f('pk_task_assignee'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_assignee')
    # ### end Alembic commands ###
