"""buat tabel task

Revision ID: 71c0cc7f7fea
Revises: 6173db9a8810
Create Date: 2025-08-13 10:01:36.229171

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '71c0cc7f7fea'
down_revision: Union[str, None] = '6173db9a8810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.Enum('TASK', 'MILESTONE', 'SECTION', name='resource_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='status_task'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority_level'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('total_time_logged', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['task.id'], name=op.f('fk_task_parent_id_task')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_task_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.execute("DROP TYPE IF EXISTS resource_type;")
    op.execute("DROP TYPE IF EXISTS status_task;")
    op.execute("DROP TYPE IF EXISTS priority_level;")
    # ### end Alembic commands ###
