"""create tabel role

Revision ID: 29061717e164
Revises: 71c0cc7f7fea
Create Date: 2025-08-13 22:20:13.824903

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '29061717e164'
down_revision: Union[str, None] = '71c0cc7f7fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'TEAM_MEMBER', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_role')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_role_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.execute("DROP TYPE IF EXISTS role;")
    # ### end Alembic commands ###
