"""update field task model

Revision ID: d81b33c34b2e
Revises: d83a446df01d
Create Date: 2025-09-02 06:28:54.191381

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd81b33c34b2e'
down_revision: Union[str, None] = 'd83a446df01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('milestone_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_task_milestone_id_milestone'), 'task', 'milestone', ['milestone_id'], ['id'])
    op.drop_column('task', 'resource_type')
    op.execute("DROP TYPE IF EXISTS resource_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    resource_type = postgresql.ENUM('TASK', 'MILESTONE', name='resource_type')
    resource_type.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'task',
        sa.Column('resource_type', resource_type, autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f('fk_task_milestone_id_milestone'), 'task', type_='foreignkey')
    op.drop_column('task', 'milestone_id')
    # ### end Alembic commands ###
