"""update relasi task

Revision ID: 80334e4a171b
Revises: edcf96410947
Create Date: 2025-09-08 22:58:34.013891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80334e4a171b'
down_revision: Union[str, None] = 'edcf96410947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_attachment_task_id_task'), 'attachment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_attachment_task_id_task'), 'attachment', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_comment_task_id_task'), 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comment_task_id_task'), 'comment', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_task_parent_id_task'), 'task', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_parent_id_task'), 'task', 'task', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_task_assignee_task_id_task'), 'task_assignee', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_assignee_task_id_task'), 'task_assignee', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_task_assignee_task_id_task'), 'task_assignee', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_assignee_task_id_task'), 'task_assignee', 'task', ['task_id'], ['id'])
    op.drop_constraint(op.f('fk_task_parent_id_task'), 'task', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_parent_id_task'), 'task', 'task', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_comment_task_id_task'), 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comment_task_id_task'), 'comment', 'task', ['task_id'], ['id'])
    op.drop_constraint(op.f('fk_attachment_task_id_task'), 'attachment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_attachment_task_id_task'), 'attachment', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###
