"""create tabel milestone

Revision ID: c623ac71805b
Revises: a8ed539054bc
Create Date: 2025-09-01 21:17:38.679504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c623ac71805b'
down_revision: Union[str, None] = 'a8ed539054bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_milestone_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestone'))
    )
    op.create_index(op.f('ix_milestone_id'), 'milestone', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milestone_id'), table_name='milestone')
    op.drop_table('milestone')
    # ### end Alembic commands ###
