"""buat tabel tugas

Revision ID: 0b53e213f2aa
Revises: 156f050a4602
Create Date: 2025-08-11 21:23:00.616148

"""
from typing import Sequence, Union

import fastapi_utils.guid_type
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0b53e213f2aa'
down_revision: Union[str, None] = '156f050a4602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tugas',
    sa.Column('id', fastapi_utils.guid_type.GUID(), nullable=False),
    sa.Column('judul', sa.String(), nullable=False),
    sa.Column('deskripsi', sa.String(), nullable=True),
    sa.Column('tipe_sumber_daya', sa.Enum('TUGAS', 'SUB_TUGAS', 'MILESTONE', 'APPROVAL', name='jenistugastype'), nullable=False),
    sa.Column('status_penyelesaian', sa.Enum('TODO', 'DONE', 'APPROVED', name='statuspenyeelesaiantype'), nullable=False),
    sa.Column('prioritas', sa.Enum('TINGGI', 'SEDANG', 'RENDAH', name='prioritastype'), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('tenggat_waktu', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mulai_waktu', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimasi_waktu', sa.Integer(), nullable=True),
    sa.Column('total_waktu_tercatat', sa.Integer(), nullable=True),
    sa.Column('create_by_id', sa.Integer(), nullable=False),
    sa.Column('tugas_induk_id', fastapi_utils.guid_type.GUID(), nullable=True),
    sa.Column('proyek_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proyek_id'], ['proyek.id'], name=op.f('fk_tugas_proyek_id_proyek')),
    sa.ForeignKeyConstraint(['tugas_induk_id'], ['tugas.id'], name=op.f('fk_tugas_tugas_induk_id_tugas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tugas'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tugas')
    op.execute("DROP TYPE IF EXISTS jenistugastype;")
    op.execute("DROP TYPE IF EXISTS statuspenyeelesaiantype;")
    op.execute("DROP TYPE IF EXISTS prioritastype;")
    # ### end Alembic commands ###
