"""add field dislay order at milestone

Revision ID: d83a446df01d
Revises: c623ac71805b
Create Date: 2025-09-01 22:33:34.141508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83a446df01d'
down_revision: Union[str, None] = 'c623ac71805b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('display_order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestone', 'display_order')
    # ### end Alembic commands ###
