"""update field audit log

Revision ID: 0161889c5f85
Revises: 61e1d85e88a6
Create Date: 2025-08-26 14:13:32.090808

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0161889c5f85'
down_revision: Union[str, None] = '61e1d85e88a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'user_id', new_column_name='performed_by')
    op.alter_column('audit_log', 'detail', new_column_name='details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'details', new_column_name='detail')
    op.alter_column('audit_log', 'performed_by', new_column_name='user_id')
    # ### end Alembic commands ###
