"""create tabel project member

Revision ID: 4e9b83e11c72
Revises: 29061717e164
Create Date: 2025-08-16 21:03:49.279957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9b83e11c72'
down_revision: Union[str, None] = '29061717e164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_member',
    sa.Column('project_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'CONTRIBUTOR', 'VIEWER', name='role_project'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_member_project_id_project')),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name=op.f('pk_project_member'))
    )
    op.create_unique_constraint(op.f('uq_user_role_user_id'), 'user_role', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_role_user_id'), 'user_role', type_='unique')
    op.drop_table('project_member')
    # ### end Alembic commands ###
