"""create tabel category

Revision ID: 2f93c4ba8214
Revises: 55d99e3c33c7
Create Date: 2025-09-07 20:53:58.643097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f93c4ba8214'
down_revision: Union[str, None] = '55d99e3c33c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_category_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_project_id'), 'category', ['project_id'], unique=False)
    op.add_column('task', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('fk_task_parent_id_task'), 'task', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_project_id_project'), 'task', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_parent_id_task'), 'task', 'task', ['parent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_task_category_id_category'), 'task', 'category', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_task_project_id_project'), 'task', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_task_project_id_project'), 'task', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_category_id_category'), 'task', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_parent_id_task'), 'task', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_project_id_project'), 'task', 'project', ['project_id'], ['id'])
    op.create_foreign_key(op.f('fk_task_parent_id_task'), 'task', 'task', ['parent_id'], ['id'])
    op.drop_column('task', 'category_id')
    op.drop_index(op.f('ix_category_project_id'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
