"""update tabel attachment

Revision ID: 55d99e3c33c7
Revises: 8a542d320ed5
Create Date: 2025-09-02 12:33:41.310448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d99e3c33c7'
down_revision: Union[str, None] = '8a542d320ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('mime_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachment', 'mime_type')
    # ### end Alembic commands ###
