"""hapus_field_assigned_to

Revision ID: 5b920484af7d
Revises: 4e9b83e11c72
Create Date: 2025-08-21 11:50:27.004485

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5b920484af7d'
down_revision: Union[str, None] = '4e9b83e11c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'assigned_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
