"""update relasi project member

Revision ID: 9e58337ba18c
Revises: 80334e4a171b
Create Date: 2025-09-09 21:32:01.299359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e58337ba18c'
down_revision: Union[str, None] = '80334e4a171b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_project_member_project_id_project'), 'project_member', type_='foreignkey')
    op.create_foreign_key(op.f('fk_project_member_project_id_project'), 'project_member', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_project_member_project_id_project'), 'project_member', type_='foreignkey')
    op.create_foreign_key(op.f('fk_project_member_project_id_project'), 'project_member', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
