"""menambahkan field penugasan ke user

Revision ID: 4ebb7f571578
Revises: 0b53e213f2aa
Create Date: 2025-08-11 21:35:21.647447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebb7f571578'
down_revision: Union[str, None] = '0b53e213f2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tugas', sa.Column('ditugaskan_ke', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tugas', 'ditugaskan_ke')
    # ### end Alembic commands ###
