"""remove relasi audit log on task

Revision ID: e858cc5d3820
Revises: 2f93c4ba8214
Create Date: 2025-09-07 22:54:18.776172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e858cc5d3820'
down_revision: Union[str, None] = '2f93c4ba8214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_audit_log_task_id_task'), 'audit_log', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_audit_log_task_id_task'), 'audit_log', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###
